### ISSUE TITLE
Can't fire notification when application is closed

### ISSUE THREAD

**Issue by rodolphorosa** [Wizcorp/phonegap-plugin-localNotifications#14] opened 2014-03-26 16:33 UTC
I've tried to install this plugin and it worked fine while application was on, but, when application is closed, the notification is not fired in android 2.3 (in android 4.3 it's fired but the logcat shows many errors concerning to AlarmReceiver). I would like to know how this solve this problem. I'm using phonegap 3.4.0.

ps.: sorry for my bad english :)

**Comment by fean** [comment] 2014-03-26 16:56
Not a problem, can you please post the stacktrace so that we can take a look at the error.

**Comment by rodolphorosa** [comment] 2014-03-26 17:05
03-26 14:03:58.496: E/AndroidRuntime(16295): FATAL EXCEPTION: main
03-26 14:03:58.496: E/AndroidRuntime(16295): java.lang.RuntimeException: Unable to start receiver jp.wizcorp.phonegap.plugin.localNotification.AlarmReceiver: java.lang.NullPointerException
03-26 14:03:58.496: E/AndroidRuntime(16295):    at android.app.ActivityThread.handleReceiver(ActivityThread.java:2372)
03-26 14:03:58.496: E/AndroidRuntime(16295):    at android.app.ActivityThread.access$1500(ActivityThread.java:149)
03-26 14:03:58.496: E/AndroidRuntime(16295):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
03-26 14:03:58.496: E/AndroidRuntime(16295):    at android.os.Handler.dispatchMessage(Handler.java:99)
03-26 14:03:58.496: E/AndroidRuntime(16295):    at android.os.Looper.loop(Looper.java:153)
03-26 14:03:58.496: E/AndroidRuntime(16295):    at android.app.ActivityThread.main(ActivityThread.java:4987)
03-26 14:03:58.496: E/AndroidRuntime(16295):    at java.lang.reflect.Method.invokeNative(Native Method)
03-26 14:03:58.496: E/AndroidRuntime(16295):    at java.lang.reflect.Method.invoke(Method.java:511)
03-26 14:03:58.496: E/AndroidRuntime(16295):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
03-26 14:03:58.496: E/AndroidRuntime(16295):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
03-26 14:03:58.496: E/AndroidRuntime(16295):    at dalvik.system.NativeStart.main(Native Method)
03-26 14:03:58.496: E/AndroidRuntime(16295): Caused by: java.lang.NullPointerException
03-26 14:03:58.496: E/AndroidRuntime(16295):    at jp.wizcorp.phonegap.plugin.localNotification.AlarmReceiver.onReceive(AlarmReceiver.java:71)
03-26 14:03:58.496: E/AndroidRuntime(16295):    at android.app.ActivityThread.handleReceiver(ActivityThread.java:2365)
03-26 14:03:58.496: E/AndroidRuntime(16295):    ... 10 more

These are the error that are shown in log cat when notification is fired and app is closed.

**Comment by fean** [comment] 2014-03-26 17:24
I'll look info it. First I Will try recreate the environment. Can you tell me which options you set in the JavaScript function?

**Comment by rodolphorosa** [comment] 2014-03-26 17:34
I used the same function that is in the code posted on github with a small adaptation (just for a brief test):

function addNotification( scheduleImmediately ) {
    var msg = prompt("Please enter a notification message:","A coleta chegou!");
    if ( msg ) {
        var seconds = parseInt(prompt("Please enter a time interval in seconds (integer):", 30));
        if ( seconds ) {
            var badge = parseInt(prompt("Please enter a badge value (integer):", 1));
            if ( badge ) {
                var options = {
                    "message" : msg,
                    "seconds" : seconds,
                    "badge" : badge,
                };
                if ( scheduleImmediately ) {
                    window.localNotification.add("GAME_NOTIFICATION", options);
                    alert("Successfully scheduled:\n" + JSON.stringify(options));
                } else {
                    window.localNotification.queue("COME_BACK_AND_PLAY", options);
                    alert("Successfully queued (will be scheduled after quitting the app):\n" + JSON.stringify(options));
                }
            }
        }
    }
}

**Comment by rodolphorosa** [comment] 2014-03-26 17:38
The cordovaExample has the same errors

**Comment by aogilvie** [comment] 2014-03-27 02:42
I've tested on Xperia 10x running 2.3.3 and not seeing any issues.
The only changes I made was to add `android-support-v13.jar` and
`Notification notification = new Notification.Builder(context)`
to
`Notification notification = new NotificationCompat.Builder(context)`

(`import android.support.v4.app.NotificationCompat;`)

The next PR is updating the example project, can you give that a try on your 2.3 device?

**Comment by fean** [comment] 2014-03-27 12:09
I'm also not getting any errors, maybe the solution @aogilvie proposed also works in your case. Let us know if it does.

**Comment by rodolphorosa** [comment] 2014-03-27 12:18
Is it working when application is closed? The only problem is that when I close the application the notification is not fired, and it only happens with 2.3 (in 4.3 a message is shown: unfortunaty, your application was closed). It seems to me that AlarmReceiver needs to be open so that the it works.

**Comment by rodolphorosa** [comment] 2014-03-31 18:37
I've followed all this steps, but it keeps not working. It show the same errors.

**Comment by aogilvie** [comment] 2014-04-01 01:55
@rodolphorosa Do you mean closed app or background state?

Some extra steps incase you cannot find `android-support-v13.jar` :
- Remember to download the support library in the SDK
  ![screen shot 2014-04-01 at 10 50 02 am](https://cloud.githubusercontent.com/assets/970364/2574916/a6607112-b940-11e3-8e57-f5afc64a5dbf.png)
- Navigate in your SDK to `sdk/extras/android/support/v13/android-support-v13.jar`

**Comment by rodolphorosa** [comment] 2014-04-01 17:16
I've added this library to my project, but it keeps showing the same errors. And I mean closed app.

**Comment by aogilvie** [comment] 2014-04-02 04:46
@rodolphorosa I have found the issue. I'm working on the fix. The problem is that the BroadcastReceiver gets the notification but tries to call 
`LocalNotification.getCordovaWebView().sendJavascript("cordova.fireDocumentEvent('receivedLocalNotification', { active : true, notificationId : " + notificationId + " })");
`
of course, this is producing a `null` error. The fix is to properly boot the application from cold and pass the state `openFromNotification` in an intent to `LocalNotification.class`.

**Comment by Gubolin** [comment] 2014-04-23 15:17
I also experience this problem. How long will the fix take? If I understand @aogilvie correctly, the plugin fires an event and is unsuccessful. I by myself don't need this event, so it could be simply deleted from the code to remove this error.

**Comment by aogilvie** [comment] 2014-06-30 03:17
Fixed with https://github.com/Wizcorp/phonegap-plugin-localNotifications/commit/34ba521184032bceb1f615401906546b8beced80
Application no longer crashes. But application cannot yet receive the notification from cold closed.
Will close this and open a enhancement issue.
(Updated on develop and master)

**Closed as completed by aogilvie** 2014-06-30 03:17 UTC
