### ISSUE TITLE
triggering only one notification 

### ISSUE THREAD

**Issue by avishayhajbi** [Wizcorp/phonegap-plugin-localNotifications#22] opened 2014-08-26 21:56 UTC
i'm using cordova 3.5.0 and when i execute two notification with different id 
only the last notification appear.
how to fix it ?

**Comment by aogilvie** [comment] 2014-09-03 06:01
Please post sample code, length of the string and the platform you are using.

**Comment by avishayhajbi** [comment] 2014-09-15 05:54
var time = new Date().getTime();
var options= {
            repeat : 'yearly',
            seconds : 1,
            title : "notification",
            message :  "somthing",
            icon : "icon",
            badge : time
        };
        localNotification.add(time,options);

that's my code .

**Comment by aogilvie** [comment] 2014-09-16 02:12
@avishayhajbi what platform and device?

**Comment by avishayhajbi** [comment] 2014-09-16 08:12
device galaxy s3 
platform 
phonegap 3.4.0
cordova 3.5.0

**Comment by aogilvie** [comment] 2014-10-06 07:53
@avishayhajbi 
sorry for the late reply:

I was not able to reproduce your problem. Your code only shows one notification. I was able to make two notifications. I push a fix to use callbacks to the `add()` api. Here is a working example below:

```
var options = {
    "message" : "testing",
    "seconds" : 10,
    "badge" : 1,
    "title" : "first"
};
window.localNotification.add(1, options, function () {

    successCb();
    var newOptions = {
        "message" : "testing",
        "seconds" : 11,
        "badge" : 1,
        "title" : "second"
    };
    window.localNotification.add(2, newOptions, function () {
        alert("second finished");
        successCb();
        }, failureCb);

}, failureCb);
```

![screenshot_2014-10-06-16-51-49](https://cloud.githubusercontent.com/assets/970364/4522723/c85b09e0-4d2d-11e4-9d88-2670de66cfd7.png)

**Comment by aogilvie** [comment] 2014-12-24 03:58
No reply. Closing.

**Closed as completed by aogilvie** 2014-12-24 03:58 UTC
